export * from './a1z-category/a1z-category';
export * from './academic-year/academic-year.model';
export * from './administration-office/administration-office.model';
export * from './exam-site/exam-site.model';
export * from './city/city.model';
export * from './exam-site/exam-site.model';
export * from './exam-subject/exam-subject.model';
export * from './exam-type/exam-type.model';
export * from './exam-version/exam-version.model';
export * from './gender/gender.model';
export * from './high-school/high-school.model';
export * from './menu/menu.model';
export * from './profile-group/profile-group.model';
export * from './profile/profile.model';
export * from './region/region.model';
export * from './roles/role.model';
export * from './study-program/study-program.model';
export * from './study-subject/study-subject.model';
export * from './universities/university.model';
export * from './university-departments/university-department.model';
export * from './user/user.model';
export * from './students/students.model';

export * from './exam-type/exam-type.model';
export * from './exam-subject/exam-subject.model';
export * from './region/region.model'
export * from './city/city.model'
export * from './academic-year/academic-year.model'
export * from './a1z-category/a1z-category'
export * from './exam-date/exam-date.model'
// export * from './folders/folders.model'
export * from './students/student-section.model'
export * from './students/student-class.model'
export * from './exam-subject-profile/exam-subject-profile.model';
export * from './student-ban/student-ban.model'
