
 export const ADMINISTRATION_OFFICE_QUERY = `
  query AdministrationOffice($pagesize: Int, $skip: Int) {
    administrationOffice(take: $pagesize, skip: $skip) {
    totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
     items {
            auditHostname
            auditSIDUsername
            auditUsername
            auditOperation
            auditTimestamp
            name
            directorName
            isRegionalOffice
            parentOfficeId
            isAllowedToLogin
            id
            isDeleted
            createdBy
            createdIP
            createdOn
            deletedBy
            deletedIP
            deletedOn
            modifiedBy
            modifiedIP
            modifiedOn
            parentOffice {
                name
                directorName
                isRegionalOffice
                parentOfficeId
                isAllowedToLogin
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
            }
            city {
                isCity
                name
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
                region {
                    name
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
            }
        }
    }
  }
`;
export const EXAM_TYPE_QUERY = `
  query ExamType($pagesize: Int, $skip: Int) {
    examType(take: $pagesize, skip: $skip) {
    totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      items {
            auditHostname
            auditSIDUsername
            auditUsername
            auditOperation
            auditTimestamp
            name
            isFall
            maximumValueWritingScore
            maximumValueMultipleScore
            id
            isDeleted
            createdBy
            createdIP
            createdOn
            deletedBy
            deletedIP
            deletedOn
            modifiedBy
            modifiedIP
            modifiedOn
        }
    }
  }
`;
export const STUDENTS = `
  query Students($pagesize: Int, $skip: Int) {
    students(take: $pagesize, skip: $skip) {
    totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
       }
        items {
            auditHostname
            auditSIDUsername
            auditUsername
            auditOperation
            auditTimestamp
            birthDate
            birthPlace
            isConfirmedBySupervisor
            isAN
            email
            firstName
            idCard
            isA2A3
            isEAlbaniaApplication
            lastName
            middleName
            mobilePhone
            oldID
            schoolFinished
            schoolName
            session
            studentId
            studyClass
            graduationYear
            isFall
            isPrinted
            diplomaPrintedDate
            id
            isDeleted
            createdBy
            createdIP
            createdOn
            deletedBy
            deletedIP
            deletedOn
            modifiedBy
            modifiedIP
            modifiedOn
            gender {
                name
            }
            highSchool {
                code
                name
                administrationOfficeId
                id
                modifiedBy
                modifiedIP
                modifiedOn
                administrationOffice {
                    name
                    directorName
                    isAllowedToLogin
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                    city {
                        name
                        region {
                            name
                        }
                    }
                    parentOffice {
                        name
                        directorName
                    }
                }
                deletedOn
                deletedIP
                deletedBy
                createdIP
                createdBy
                isDeleted
                createdOn
                isPublic
                cityId
                city {
                    isCity
                    name
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                    region {
                        name
                        id
                        isDeleted
                        createdBy
                        createdIP
                        createdOn
                        deletedBy
                        deletedIP
                        deletedOn
                        modifiedBy
                        modifiedIP
                        modifiedOn
                    }
                }
                regionId
                region {
                    name
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
            }
            profile {
                code
                name
                isTechnical
                d1Coefficient
                d2Coefficient
                fullName
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
                academicYear {
                    isActive
                    year
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
                profileGroup {
                    name
                    ordering
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
            }
            registrationYear {
                isActive
                year
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
            }
        }

      }
      }


`
export const CARRIED_GRADE = `
  query CarriedGrade($pagesize: Int, $skip: Int) {
    carriedGrade(take: $pagesize, skip: $skip) {
    totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
       }

        items {
            auditHostname
            auditSIDUsername
            auditUsername
            auditOperation
            auditTimestamp
            nid
            examSubject
            year
            grade
            document
            id
            isDeleted
            createdBy
            createdIP
            createdOn
            deletedBy
            deletedIP
            deletedOn
            modifiedBy
            modifiedIP
            modifiedOn
            examType {
                name
                isFall
                maximumValueWritingScore
                maximumValueMultipleScore
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
            }
        }

      }
      }

`;

export const A1_FORMS = `
  query A1Forms($pagesize: Int, $skip: Int) {
    a1Forms(take: $pagesize, skip: $skip) {
    totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
   items {
            auditHostname
            auditSIDUsername
            auditUsername
            auditOperation
            auditTimestamp
            scoreD1
            reasonD1
            yearD1
            subjectNameD1
            scoreD2
            reasonD2
            yearD2
            subjectNameD2
            scoreD3
            reasonD3
            yearD3
            subjectNameD3
            scoreZ1
            reasonZ1
            yearZ1
            subjectNameZ1
            scoreZ2
            reasonZ2
            yearZ2
            subjectNameZ2
            scoreZ3
            reasonZ3
            yearZ3
            subjectNameZ3
            highSchoolGraduationYear
            isApplyingToForeignCountries
            alreadyHaveDiploma
            isEAlbaniaApplication
            isA1
            printedOn
            id
            isDeleted
            createdBy
            createdIP
            createdOn
            deletedBy
            deletedIP
            deletedOn
            modifiedBy
            modifiedIP
            modifiedOn
            subjectD1 {
                code
                name
                credits
                isOptional
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
                examType {
                    name
                    isFall
                    maximumValueWritingScore
                    maximumValueMultipleScore
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
                academicYear {
                    isActive
                    year
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
            }
            subjectD2 {
                code
                name
                credits
                isOptional
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
                examType {
                    name
                    isFall
                    maximumValueWritingScore
                    maximumValueMultipleScore
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
                academicYear {
                    isActive
                    year
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
            }
            subjectD3 {
                code
                name
                credits
                isOptional
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
                examType {
                    name
                    isFall
                    maximumValueWritingScore
                    maximumValueMultipleScore
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
                academicYear {
                    isActive
                    year
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
            }
            subjectZ1 {
                code
                name
                credits
                isOptional
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
                examType {
                    name
                    isFall
                    maximumValueWritingScore
                    maximumValueMultipleScore
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
                academicYear {
                    isActive
                    year
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
            }
            subjectZ2 {
                code
                name
                credits
                isOptional
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
                examType {
                    name
                    isFall
                    maximumValueWritingScore
                    maximumValueMultipleScore
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
                academicYear {
                    isActive
                    year
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
            }
            subjectZ3 {
                code
                name
                credits
                isOptional
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
                examType {
                    name
                    isFall
                    maximumValueWritingScore
                    maximumValueMultipleScore
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
                academicYear {
                    isActive
                    year
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
            }
            a1ZCategory {
                name
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
            }
            academicYear {
                isActive
                year
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
            }
            student {
                birthDate
                birthPlace
                isConfirmedBySupervisor
                isAN
                email
                firstName
                idCard
                isA2A3
                isEAlbaniaApplication
                lastName
                middleName
                mobilePhone
                oldID
                schoolFinished
                schoolName
                session
                studentId
                studyClass
                graduationYear
                isFall
                isPrinted
                diplomaPrintedDate
                id
                isDeleted
                createdBy
                createdIP
                createdOn
                deletedBy
                deletedIP
                deletedOn
                modifiedBy
                modifiedIP
                modifiedOn
                gender {
                    name
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
                highSchool {
                    code
                    name
                    isPublic
                    administrationOfficeId
                    cityId
                    regionId
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                    administrationOffice {
                        name
                        directorName
                        isRegionalOffice
                        parentOfficeId
                        signature
                        isAllowedToLogin
                        id
                        isDeleted
                        createdBy
                        createdIP
                        createdOn
                        deletedBy
                        deletedIP
                        deletedOn
                        modifiedBy
                        modifiedIP
                        modifiedOn
                        parentOffice {
                            name
                            directorName
                            isRegionalOffice
                            parentOfficeId
                            signature
                            isAllowedToLogin
                            id
                            isDeleted
                            createdBy
                            createdIP
                            createdOn
                            deletedBy
                            deletedIP
                            deletedOn
                            modifiedBy
                            modifiedIP
                            modifiedOn
                            parentOffice {
                                name
                                directorName
                                isRegionalOffice
                                parentOfficeId
                                signature
                                isAllowedToLogin
                                id
                                isDeleted
                                createdBy
                                createdIP
                                createdOn
                                deletedBy
                                deletedIP
                                deletedOn
                                modifiedBy
                                modifiedIP
                                modifiedOn
                                parentOffice {
                                    name
                                    directorName
                                    isRegionalOffice
                                    parentOfficeId
                                    signature
                                    isAllowedToLogin
                                    id
                                    isDeleted
                                    createdBy
                                    createdIP
                                    createdOn
                                    deletedBy
                                    deletedIP
                                    deletedOn
                                    modifiedBy
                                    modifiedIP
                                    modifiedOn
                                    parentOffice {
                                        name
                                        directorName
                                        isRegionalOffice
                                        parentOfficeId
                                        signature
                                        isAllowedToLogin
                                        id
                                        isDeleted
                                        createdBy
                                        createdIP
                                        createdOn
                                        deletedBy
                                        deletedIP
                                        deletedOn
                                        modifiedBy
                                        modifiedIP
                                        modifiedOn
                                        parentOffice {
                                            name
                                            directorName
                                            isRegionalOffice
                                            parentOfficeId
                                            signature
                                            isAllowedToLogin
                                            id
                                            isDeleted
                                            createdBy
                                            createdIP
                                            createdOn
                                            deletedBy
                                            deletedIP
                                            deletedOn
                                            modifiedBy
                                            modifiedIP
                                            modifiedOn
                                            parentOffice {
                                                name
                                                directorName
                                                isRegionalOffice
                                                parentOfficeId
                                                signature
                                                isAllowedToLogin
                                                id
                                                isDeleted
                                                createdBy
                                                createdIP
                                                createdOn
                                                deletedBy
                                                deletedIP
                                                deletedOn
                                                modifiedBy
                                                modifiedIP
                                                modifiedOn
                                                parentOffice {
                                                    name
                                                    directorName
                                                    isRegionalOffice
                                                    parentOfficeId
                                                    signature
                                                    isAllowedToLogin
                                                    id
                                                    isDeleted
                                                    createdBy
                                                    createdIP
                                                    createdOn
                                                    deletedBy
                                                    deletedIP
                                                    deletedOn
                                                    modifiedBy
                                                    modifiedIP
                                                    modifiedOn
                                                    parentOffice {
                                                        name
                                                        directorName
                                                        isRegionalOffice
                                                        parentOfficeId
                                                        isAllowedToLogin
                                                        id
                                                        isDeleted
                                                        createdBy
                                                        createdIP
                                                        createdOn
                                                        deletedBy
                                                        deletedIP
                                                        deletedOn
                                                        modifiedBy
                                                        modifiedIP
                                                        modifiedOn
                                                        parentOffice {
                                                            name
                                                            directorName
                                                            isRegionalOffice
                                                            parentOfficeId
                                                            signature
                                                            isAllowedToLogin
                                                            id
                                                            isDeleted
                                                            createdBy
                                                            createdIP
                                                            createdOn
                                                            deletedBy
                                                            deletedIP
                                                            deletedOn
                                                            modifiedBy
                                                            modifiedIP
                                                            modifiedOn
                                                            parentOffice {
                                                                name
                                                                directorName
                                                                isRegionalOffice
                                                                parentOfficeId
                                                                signature
                                                                isAllowedToLogin
                                                                id
                                                                isDeleted
                                                                createdBy
                                                                createdIP
                                                                createdOn
                                                                deletedBy
                                                                deletedIP
                                                                deletedOn
                                                                modifiedBy
                                                                modifiedIP
                                                                modifiedOn
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                profile {
                    code
                    name
                    isTechnical
                    d1Coefficient
                    d2Coefficient
                    fullName
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                    academicYear {
                        isActive
                        year
                        id
                        isDeleted
                        createdBy
                        createdIP
                        createdOn
                        deletedBy
                        deletedIP
                        deletedOn
                        modifiedBy
                        modifiedIP
                        modifiedOn
                    }
                    profileGroup {
                        name
                        ordering
                        id
                        isDeleted
                        createdBy
                        createdIP
                        createdOn
                        deletedBy
                        deletedIP
                        deletedOn
                        modifiedBy
                        modifiedIP
                        modifiedOn
                    }
                }
                registrationYear {
                    isActive
                    year
                    id
                    isDeleted
                    createdBy
                    createdIP
                    createdOn
                    deletedBy
                    deletedIP
                    deletedOn
                    modifiedBy
                    modifiedIP
                    modifiedOn
                }
            }
        }


      }
      }
      `
 export const queriesMap: Map<string, string> = new Map([
   ['a1Forms', A1_FORMS],
   ['students', STUDENTS],
   ['administrationOffice', ADMINISTRATION_OFFICE_QUERY],
   ['examType', EXAM_TYPE_QUERY],
   ['carriedGrade', CARRIED_GRADE],
 ]);
