export * from './lib/archive-exam/archive-exam-api.service';
export * from './lib/archive-folder/archive-folder-api.service';
export * from './lib/calculation-processes/calculation-processes-api.service';
export * from './lib/exam-grade/exam-grade-api.service';
export * from './lib/annual-grades/annual-grades-api.service';
export * from './lib/exam-score/exam-score-api.service';
export * from './lib/exam-secret/exam-secret-api.service';
export * from './lib/grades-scale/grades-scale-api.service';
export * from './lib/unmatched-exams/unmatched-exams-api.service';
