export const roleList = [
  {
    roleName: 'Admin',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: true,
    showHighSchools: false,
  },

  {
    roleName: 'ZVAP',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: true,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleName: 'Secrets',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleName: 'DV (Drejtoria e Vlerësimit)',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleName: 'Mbikqyres Formularesh',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: true,
    showOverseerCode: true,
  },
  {
    roleName: 'Operator',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: false,
    showOverseerCode: false,
  },
  {
    roleName: 'HighSchool',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: true,
    showOverseerCode: false,
  },
];

export enum RoleName {
  Admin = 'Admin',
  ZVAP = 'ZVAP',
  Secrets = 'Secrets',
  DV = 'DV (Drejtoria e Vlerësimit)',
  MbikqyresFormularesh = 'Mbikqyres Formularesh',
  Operator = 'Operator',
  HighSchool = 'HighSchool',
}
