export const roleList = [
  {
    roleCode: 'AKP',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },

  {
    roleCode: 'DAR/ZA',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: true,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleCode: 'Administrim Testi',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleCode: 'Auditor',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleCode: 'DV',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleCode: 'Dekan',
    showUniversities: true,
    showUniversityDepartment: true,
    showAdministrationOffice: false,
    showStudyProgram: true,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleCode: 'Fakultet',
    showUniversities: true,
    showUniversityDepartment: true,
    showAdministrationOffice: false,
    showStudyProgram: true,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleCode: 'Kontrolluesi',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleCode: 'MASH',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showOverseerCode: false,
    showStudyProgram: false,
    showHighSchools: false,
  },
  {
    roleCode: 'Maturant',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: false,
    showOverseerCode: false,
  },
  {
    roleCode: 'Mbikqyres Formularesh',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: true,
    showOverseerCode: true,
  },
  {
    roleCode: 'Operator',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: false,
    showOverseerCode: false,
  },
  {
    roleCode: 'Operator A2',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: false,
    showOverseerCode: false,
  },
  {
    roleCode: 'Operator korrigjim pasaktesie',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: false,
    showOverseerCode: false,
  },
  {
    roleCode: 'Shkolla',
    showUniversities: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: true,
    showOverseerCode: false,
  },
];

export const rolesDropDown = [
  {
    key: 1,
    value: 'AKP',
  },
  {
    key: 2,
    value: 'DAR/ZA',
  },
  {
    key: 3,
    value: 'Shkolla',
  },
  {
    key: 5,
    value: 'Fakultet',
  },
  {
    key: 6,
    value: 'Maturant',
  },
  {
    key: 7,
    value: 'MASH',
  },
  {
    key: 8,
    value: 'Dekan',
  },
  {
    key: 9,
    value: 'Operator A2',
  },
  {
    key: 10,
    value: 'Mbikqyres Formularesh',
  },
  {
    key: 11,
    value: 'Kontrolluesi',
  },
  {
    key: 12,
    value: 'Operator',
  },
  {
    key: 13,
    value: 'Auditor',
  },
  {
    key: 14,
    value: 'Administrim Testi',
  },
  {
    key: 15,
    value: 'DV',
  },
  {
    key: 16,
    value: 'Operator korrigjim pasaktesie',
  },
];
