export const roleList = [
  {
    roleName: 'Admin',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: true,
    showHighSchools: false,
  },

  {
    roleName: 'ZVAP',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: true,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleName: 'ExamManager',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleName: 'Auditor',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleName: 'DV (Drejtoria e Vlerësimit)',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleName: 'University',
    showUniversity: true,
    showUniversityDepartment: true,
    showAdministrationOffice: false,
    showStudyProgram: true,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleName: 'UniversityDepartment',
    showUniversity: true,
    showUniversityDepartment: true,
    showAdministrationOffice: false,
    showStudyProgram: true,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleName: 'Controller',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showOverseerCode: false,
    showHighSchools: false,
  },
  {
    roleName: 'Student',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: false,
    showOverseerCode: false,
  },
  {
    roleName: 'Mbikqyres Formularesh',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: true,
    showOverseerCode: true,
  },
  {
    roleName: 'Operator',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: false,
    showOverseerCode: false,
  },
  {
    roleName: 'A2Operator',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: false,
    showOverseerCode: false,
  },
  {
    roleName: 'CorrectionsOperator',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: false,
    showOverseerCode: false,
  },
  {
    roleName: 'HighSchool',
    showUniversity: false,
    showUniversityDepartment: false,
    showAdministrationOffice: false,
    showStudyProgram: false,
    showHighSchools: true,
    showOverseerCode: false,
  },
];
